#!/bin/bash
red='\033[0;31m'    
green='\033[0;32m'    
cyan='\033[0;36m'    
white='\033[1;37m'
if [ -d /data/data/com.termux/files/home ]; then
        systems="/data/data/com.termux/files/usr/engines"
else
        if [ $(id -u) -ne 0 ]; then
                echo "This script must be ran as root"
                exit 1
        fi
        systems="/usr/engines"
fi
echo -e "${white}+------------------------${red}OWN${white}-----------------------+"
echo -e "${white}| ${green}███████╗███╗   ██╗ ██████╗ ██╗███╗   ██╗███████╗${white} |"
echo -e "${white}| ${green}██╔════╝████╗  ██║██╔════╝ ██║████╗  ██║██╔════╝${white} |"
echo -e "${white}| ${green}█████╗  ██╔██╗ ██║██║  ███╗██║██╔██╗ ██║█████╗${white}   |"
echo -e "${white}| ${green}██╔══╝  ██║╚██╗██║██║   ██║██║██║╚██╗██║██╔══╝${white}   |"
echo -e "${white}| ${green}███████╗██║ ╚████║╚██████╔╝██║██║ ╚████║███████╗${white} |"
echo -e "${white}| ${green}╚══════╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝╚═╝  ╚═══╝╚══════╝${white} |"
echo -e "${white}+--------------------------------------------------+"
echo -e "${white}|${cyan}          Search and discover new ideas ${white}          |"
echo -e "${white}+--------------------------------------------------+"
python3 $systems/engine.py
